import {Component, Input, OnInit} from '@angular/core';
import {AmbientModel} from '../definitions/form.definitions';

@Component({
  selector: 'page-thirteen',
  styleUrls: ['./page.css'],
  templateUrl: './page-thirteen.component.html'
})
export class PageThirteenComponent implements OnInit {
  @Input()
  model: AmbientModel;

  ngOnInit() {
    this.model.properties['1308'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ687"}};
    this.model.properties['1310'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ688"}};
    this.model.properties['1311'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ689"}};
    this.model.properties['1312'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ690"}};
    this.model.properties['1313'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ691"}};
    this.model.properties['1314'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ692"}};
    this.model.properties['1315'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ693"}};
    this.model.properties['1316'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ694"}};
    this.model.properties['1317'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ695"}};
    this.model.properties['1318'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ696"}};
    this.model.properties['1319'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ697"}};
    this.model.properties['1320'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ698"}};
    this.model.properties['1321'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ699"}};
    this.model.properties['1322'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ700"}};
    this.model.properties['1323'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ701"}};
    this.model.properties['1324'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ702"}};
  }

  Input1308 = {"objectType":"memo","componentId":"1308","zIndex":0,"width":119,"height":114,"left":58,"top":49,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":263,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"119","maxLength":0};
  Input1310 = {"objectType":"memo","componentId":"1310","zIndex":1,"width":119,"height":114,"left":202,"top":49,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":264,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"119","maxLength":0};
  Input1311 = {"objectType":"memo","componentId":"1311","zIndex":2,"width":119,"height":114,"left":346,"top":49,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":265,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allUpper","maxHeight":"119","maxLength":0};
  Input1312 = {"objectType":"memo","componentId":"1312","zIndex":3,"width":119,"height":114,"left":490,"top":49,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":266,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"119","maxLength":0};
  Input1313 = {"objectType":"memo","componentId":"1313","zIndex":4,"width":119,"height":114,"left":490,"top":185,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":267,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"119","maxLength":0};
  Input1314 = {"objectType":"memo","componentId":"1314","zIndex":5,"width":119,"height":114,"left":58,"top":185,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":268,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"119","maxLength":0};
  Input1315 = {"objectType":"memo","componentId":"1315","zIndex":6,"width":119,"height":114,"left":202,"top":185,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":269,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"119","maxLength":0};
  Input1316 = {"objectType":"memo","componentId":"1316","zIndex":7,"width":119,"height":114,"left":346,"top":185,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":270,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allUpper","maxHeight":"119","maxLength":0};
  Input1317 = {"objectType":"memo","componentId":"1317","zIndex":8,"width":119,"height":114,"left":346,"top":321,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":271,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allUpper","maxHeight":"119","maxLength":0};
  Input1318 = {"objectType":"memo","componentId":"1318","zIndex":9,"width":119,"height":114,"left":490,"top":321,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":272,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"119","maxLength":0};
  Input1319 = {"objectType":"memo","componentId":"1319","zIndex":10,"width":119,"height":114,"left":58,"top":321,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":273,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allUpper","maxHeight":"119","maxLength":0};
  Input1320 = {"objectType":"memo","componentId":"1320","zIndex":11,"width":119,"height":114,"left":202,"top":321,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":274,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"119","maxLength":0};
  Input1321 = {"objectType":"memo","componentId":"1321","zIndex":12,"width":119,"height":114,"left":202,"top":457,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":275,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"119","maxLength":0};
  Input1322 = {"objectType":"memo","componentId":"1322","zIndex":13,"width":119,"height":114,"left":346,"top":457,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":276,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allUpper","maxHeight":"119","maxLength":0};
  Input1323 = {"objectType":"memo","componentId":"1323","zIndex":14,"width":119,"height":114,"left":490,"top":457,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":277,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"119","maxLength":0};
  Input1324 = {"objectType":"memo","componentId":"1324","zIndex":15,"width":119,"height":114,"left":58,"top":457,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":278,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"119","maxLength":0};
}
