import {Component, Input, OnInit} from '@angular/core';
import {AmbientModel} from '../definitions/form.definitions';

@Component({
  selector: 'page-twelve',
  styleUrls: ['./page.css'],
  templateUrl: './page-twelve.component.html'
})
export class PageTwelveComponent implements OnInit {
  @Input()
  model: AmbientModel;

  ngOnInit(): void {
    this.model.properties['479'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"#FF8000"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":7},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":true},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"yellow"},"lgiActiveLineColor":{"currentValue":"red"},"lgiLineWidth":{"currentValue":2},"lgiActiveLineWidth":{"currentValue":5},"lgiLineStyle":{"currentValue":2},"lgiActiveLineStyle":{"currentValue":1},"hint":{"currentValue":"Champ238"}};
    this.model.properties['481'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"blue"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":3},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":true},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"yellow"},"lgiActiveLineColor":{"currentValue":"red"},"lgiLineWidth":{"currentValue":2},"lgiActiveLineWidth":{"currentValue":5},"lgiLineStyle":{"currentValue":2},"lgiActiveLineStyle":{"currentValue":1},"hint":{"currentValue":"Champ239"}};
    this.model.properties['482'] = {"enabled":{"currentValue":false},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"#FF8000"},"brushColor":{"currentValue":"gray"},"brushStyle":{"currentValue":2},"activeBrushStyle":{"currentValue":7},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":true},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"yellow"},"lgiActiveLineColor":{"currentValue":"red"},"lgiLineWidth":{"currentValue":2},"lgiActiveLineWidth":{"currentValue":5},"lgiLineStyle":{"currentValue":2},"lgiActiveLineStyle":{"currentValue":1},"hint":{"currentValue":"Champ240"}};
    this.model.properties['483'] = {"enabled":{"currentValue":false},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"blue"},"brushColor":{"currentValue":"#808040"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":3},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":true},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"yellow"},"lgiActiveLineColor":{"currentValue":"red"},"lgiLineWidth":{"currentValue":4},"lgiActiveLineWidth":{"currentValue":5},"lgiLineStyle":{"currentValue":4},"lgiActiveLineStyle":{"currentValue":1},"hint":{"currentValue":"Champ241"}};
    this.model.properties['Btn484'] = {"enabled":{"currentValue":true},"visible":{"currentValue":true},"brushColor":{"currentValue":"silver"},"brushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":1}};
    this.model.properties['Btn485'] = {"enabled":{"currentValue":true},"visible":{"currentValue":true},"brushColor":{"currentValue":"silver"},"brushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":1}};
    this.model.properties['486'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ242"}};
    this.model.properties['487'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ243"}};
    this.model.properties['488'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ244"}};
    this.model.properties['490'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ245"}};
    this.model.properties['491'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ246"}};
    this.model.properties['492'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ247"}};
    this.model.properties['493'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ248"}};
    this.model.properties['494'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ249"}};
    this.model.properties['495'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ250"}};
    this.model.properties['496'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ251"}};
    this.model.properties['497'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ252"}};
    this.model.properties['498'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ253"}};
    this.model.properties['499'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ254"}};
    this.model.properties['500'] = {"enabled":{"currentValue":false},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"#FF8000"},"brushColor":{"currentValue":"gray"},"brushStyle":{"currentValue":1},"activeBrushStyle":{"currentValue":7},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"yellow"},"lgiActiveLineColor":{"currentValue":"red"},"lgiLineWidth":{"currentValue":2},"lgiActiveLineWidth":{"currentValue":5},"lgiLineStyle":{"currentValue":2},"lgiActiveLineStyle":{"currentValue":1},"hint":{"currentValue":"Champ255"}};
    this.model.properties['501'] = {"enabled":{"currentValue":false},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"blue"},"brushColor":{"currentValue":"#808040"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":3},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"yellow"},"lgiActiveLineColor":{"currentValue":"red"},"lgiLineWidth":{"currentValue":4},"lgiActiveLineWidth":{"currentValue":5},"lgiLineStyle":{"currentValue":4},"lgiActiveLineStyle":{"currentValue":1},"hint":{"currentValue":"Champ256"}};
    this.model.properties['Line502'] = {"visible":{"currentValue":true},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":1},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0}};
    this.model.properties['Line503'] = {"visible":{"currentValue":true},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":1},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0}};
    this.model.properties['504'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ257"}};
    this.model.properties['505'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"red"},"fontStyle":{"currentValue":5},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ258"}};
    this.model.properties['506'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"black"},"fontStyle":{"currentValue":10},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ259"}};
    this.model.properties['507'] = {"enabled":{"currentValue":true},"optional":{"currentValue":true},"visible":{"currentValue":true},"activeBrushColor":{"currentValue":"white"},"brushColor":{"currentValue":"white"},"brushStyle":{"currentValue":0},"activeBrushStyle":{"currentValue":0},"fontColor":{"currentValue":"red"},"fontStyle":{"currentValue":0},"lgiAfficherLigne":{"currentValue":false},"lgiActiveAfficherLigne":{"currentValue":true},"lgiLineColor":{"currentValue":"black"},"lgiActiveLineColor":{"currentValue":"black"},"lgiLineWidth":{"currentValue":1},"lgiActiveLineWidth":{"currentValue":1},"lgiLineStyle":{"currentValue":0},"lgiActiveLineStyle":{"currentValue":0},"hint":{"currentValue":"Champ260"}};
  }

  Input479 = {"objectType":"memo","componentId":"479","zIndex":0,"width":203,"height":153,"left":24,"top":24,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"blue","borderWidth":1,"inactiveBorders":"trbl","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":240,"textAlign":"left","textHeight":"14px","activeLine":{"style":1,"color":"red","thickness":5},"inactiveLine":{"style":2,"color":"yellow","thickness":2},"format":"text","maxHeight":"161","maxLength":0};
  Input481 = {"objectType":"memo","componentId":"481","zIndex":1,"width":203,"height":153,"left":249,"top":24,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"trbl","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":241,"textAlign":"left","textHeight":"14px","activeLine":{"style":1,"color":"red","thickness":5},"inactiveLine":{"style":2,"color":"yellow","thickness":2},"format":"allUpper","maxHeight":"161","maxLength":50};
  Input482 = {"objectType":"memo","componentId":"482","zIndex":2,"width":203,"height":153,"left":24,"top":199,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"trbl","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":7,"tabOrder":242,"textAlign":"left","textHeight":"14px","activeLine":{"style":1,"color":"red","thickness":5},"inactiveLine":{"style":2,"color":"yellow","thickness":2},"format":"text","maxHeight":"161","maxLength":0};
  Input483 = {"objectType":"memo","componentId":"483","zIndex":3,"width":203,"height":153,"left":249,"top":199,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"trbl","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":4,"tabOrder":243,"textAlign":"left","textHeight":"14px","activeLine":{"style":1,"color":"red","thickness":5},"inactiveLine":{"style":4,"color":"yellow","thickness":4},"format":"allUpper","maxHeight":"161","maxLength":60};
  Btn484 = {"objectType":"button","componentId":"Btn484","zIndex":4,"width":75,"height":25,"left":547,"top":220,"isTransparent":false,"text":"Activer","fontFamily":"\"Arial\"","fontStyle":"b","fontSize":"8pt"};
  Btn485 = {"objectType":"button","componentId":"Btn485","zIndex":5,"width":75,"height":25,"left":546,"top":287,"isTransparent":false,"text":"D&#233;sactiver","fontFamily":"\"Arial\"","fontStyle":"b","fontSize":"8pt"};
  Input486 = {"objectType":"memo","componentId":"486","zIndex":6,"width":102,"height":18,"left":24,"top":614,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":244,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input487 = {"objectType":"memo","componentId":"487","zIndex":7,"width":102,"height":19,"left":24,"top":639,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"b","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":245,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input488 = {"objectType":"memo","componentId":"488","zIndex":8,"width":102,"height":19,"left":24,"top":664,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"b","borderStyle":0,"borderColor":"black","borderWidth":5,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":246,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input490 = {"objectType":"memo","componentId":"490","zIndex":9,"width":103,"height":18,"left":144,"top":664,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"r","borderStyle":0,"borderColor":"black","borderWidth":5,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":247,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input491 = {"objectType":"memo","componentId":"491","zIndex":10,"width":102,"height":18,"left":259,"top":664,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"t","borderStyle":0,"borderColor":"black","borderWidth":5,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":248,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input492 = {"objectType":"memo","componentId":"492","zIndex":11,"width":102,"height":18,"left":374,"top":664,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"l","borderStyle":0,"borderColor":"black","borderWidth":5,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":249,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input493 = {"objectType":"memo","componentId":"493","zIndex":12,"width":103,"height":18,"left":489,"top":664,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"rl","borderStyle":0,"borderColor":"black","borderWidth":5,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":250,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input494 = {"objectType":"memo","componentId":"494","zIndex":13,"width":102,"height":19,"left":599,"top":664,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"tb","borderStyle":0,"borderColor":"black","borderWidth":5,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":251,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"firstUpper","maxHeight":"21","maxLength":0};
  Input495 = {"objectType":"memo","componentId":"495","zIndex":14,"width":102,"height":19,"left":24,"top":689,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"b","borderStyle":0,"borderColor":"black","borderWidth":10,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":252,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"21","maxLength":0};
  Input496 = {"objectType":"memo","componentId":"496","zIndex":15,"width":103,"height":18,"left":144,"top":689,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"r","borderStyle":0,"borderColor":"black","borderWidth":10,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":253,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"21","maxLength":0};
  Input497 = {"objectType":"memo","componentId":"497","zIndex":16,"width":102,"height":18,"left":259,"top":689,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"t","borderStyle":0,"borderColor":"black","borderWidth":10,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":254,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"21","maxLength":0};
  Input498 = {"objectType":"memo","componentId":"498","zIndex":17,"width":102,"height":18,"left":374,"top":689,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"l","borderStyle":0,"borderColor":"black","borderWidth":10,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":255,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"21","maxLength":0};
  Input499 = {"objectType":"memo","componentId":"499","zIndex":18,"width":103,"height":21,"left":489,"top":689,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"black","borderWidth":10,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":256,"textAlign":"left","textHeight":"14px","activeLine":{"style":0,"color":"black","thickness":1},"format":"allLower","maxHeight":"21","maxLength":0};
  Input500 = {"objectType":"memo","componentId":"500","zIndex":19,"width":203,"height":153,"left":24,"top":384,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"trbl","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":7,"tabOrder":257,"textAlign":"left","textHeight":"14px","activeLine":{"style":1,"color":"red","thickness":5},"format":"text","maxHeight":"161","maxLength":0};
  Input501 = {"objectType":"memo","componentId":"501","zIndex":20,"width":203,"height":153,"left":249,"top":384,"fontFamily":"\"Arial\"","fontStyle":"","fontSize":"8pt","borders":"trbl","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"trbl","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":4,"tabOrder":258,"textAlign":"left","textHeight":"14px","activeLine":{"style":1,"color":"red","thickness":5},"format":"allUpper","maxHeight":"161","maxLength":60};
  Line502 = {"objectType":"line","componentId":"Line502","zIndex":21,"width":203,"height":1,"left":24,"top":22,"x1":24,"x2":226,"y1":22,"y2":22,"lineWidth":1,"lineStyle":0,"lineColor":"#400000"};
  Line503 = {"objectType":"line","componentId":"Line503","zIndex":22,"width":1,"height":153,"left":22,"top":24,"x1":22,"x2":22,"y1":24,"y2":176,"lineWidth":1,"lineStyle":0,"lineColor":"#400000"};
  Input504 = {"objectType":"memo","componentId":"504","zIndex":23,"width":152,"height":252,"left":24,"top":724,"fontFamily":"\"Calibri\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":259,"textAlign":"left","textHeight":"13px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"253","maxLength":0};
  Input505 = {"objectType":"memo","componentId":"505","zIndex":24,"width":152,"height":252,"left":199,"top":724,"fontFamily":"\"Calibri\"","fontStyle":"bu","fontSize":"15pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":260,"textAlign":"center","textHeight":"24px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"252","maxLength":0};
  Input506 = {"objectType":"memo","componentId":"506","zIndex":25,"width":152,"height":252,"left":389,"top":724,"fontFamily":"\"Calibri\"","fontStyle":"is","fontSize":"5pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":261,"textAlign":"right","textHeight":"9px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"256","maxLength":0};
  Input507 = {"objectType":"memo","componentId":"507","zIndex":26,"width":152,"height":252,"left":579,"top":724,"fontFamily":"\"Calibri\"","fontStyle":"","fontSize":"8pt","borders":"","borderStyle":0,"borderColor":"black","borderWidth":1,"inactiveBorders":"","inactiveBorderStyle":0,"inactiveBorderColor":"black","inactiveBorderWidth":1,"tabOrder":262,"textAlign":"justify","textHeight":"13px","activeLine":{"style":0,"color":"black","thickness":1},"format":"text","maxHeight":"253","maxLength":0};
}
